Repository esmero/ami, pull requests merged in 2022-03, with the labels that each got.

#64 ISSUE-62: Checkbox not rendering in LoD cleanup
  src/Form/amiSetEntityReconcileCleanUpForm.php
Labels: bug, UI, Drupal 9

#66 Issue-65: Fix Zip based Spreadsheet formats like XSLX
  src/AmiUtilityService.php
  src/Plugin/ImporterAdapter/GoogleSheetImporter.php
  src/Plugin/ImporterAdapter/SolrImporter.php
  src/Plugin/ImporterAdapter/SpreadsheetImporter.php
  src/Plugin/ImporterAdapterBase.php
  src/Plugin/ImporterAdapterInterface.php
Labels: bug, enhancement, UI, Ingest Setup, PHP8

#72 ISSUE-71: Fix eternal re-enqueueing and Download improvements
  src/AmiUtilityService.php
  src/Form/amiSetEntityReconcileCleanUpForm.php
  src/Plugin/QueueWorker/IngestADOQueueWorker.php
Labels: bug, enhancement, queue, queue workers, LoD Reconciliation

#73 ISSUE-71b: Wrong logic! Fixes non-sense issue of wrong comparisson
  src/Plugin/QueueWorker/IngestADOQueueWorker.php
Labels: bug

#75 ISSUE-74: Improve AMI Sets Preview
  ami.services.yml
  src/AmiUtilityService.php
  src/Controller/AmiRowAutocompleteHandler.php
  src/TwigExtension.php
Labels: enhancement, UI, Drupal 9, PHP8, LoD Reconciliation, Metadata Display Preview
